import Providers from './providers';
import './globals.css';

export const metadata = {
   title: 'Paymonitor',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang='es' className='h-full bg-gray-50'>
         <body className='h-full'>
            <Providers>{children}</Providers>
         </body>
      </html>
   );
}
